### ISSUE TITLE
minishift dependancies

### ISSUE THREAD

**Issue by b3nnnn** [nmenant/ci-cd-env-setup#29]
Minishift needed libvirt and qemu-kvm dependancies met as per https://docs.okd.io/latest/minishift/getting-started/setting-up-virtualization-environment.html#for-linux on my vanilla centos image.

Also /usr/local/bin needed to be in PATH

**Comment by nmenant** [comment]
Updated the README file to highlight your link and the specific steps for a vanilla centos image. 

thanks for the tip !
